INSERT INTO customer_entity (lei,entity, entityOwner, entityContactDetails ) VALUES ('G20820052','AHHoldings International', 'Andrew Hobson', {'phone':'+61666666666','email':'andrew.h@gcc.com'});

INSERT INTO customer_entity (lei, entity, entityOwner, entityContactDetails ) VALUES ('G24707916','SAN Holdings International', 'Sanjeev Kumar', {'phone':'+617777777','email':'sanjeev.k@ecm.com'});

INSERT INTO customer_entity (lei, entity, entityOwner, entityContactDetails ) VALUES ('G55403998','BATA Groups Public Limited', 'Khanna Anand', {'phone':'+9198765211','email':'anand.kh@bata.com'});

INSERT INTO customer_entity (lei, entity, entityOwner, entityContactDetails ) VALUES ('G43103653','Federer Sports Private Limited', 'Roger Federer', {'phone':'+4487621212','email':'federer.r@fed.com'});

INSERT INTO customer_entity (lei, entity, entityOwner, entityContactDetails ) VALUES ('G43103653','Bulls and Finance Corporation', 'John Pope', {'phone':'+132322134','email':'john.pope@bull.com'});
